name: Promote candidate to stable

on:
  workflow_dispatch: # Allow manual trigger

jobs:

  check-secret:
    runs-on: ubuntu-22.04
    outputs:
      snap-key: ${{ steps.snap-key.outputs.defined }}
    steps:
      - id: snap-key
        name: Set defined=true if STORE_LOGIN is defined
        if: "${{ env.SNAPSTORE_KEY != '' }}"
        run: echo "defined=true" >> $GITHUB_OUTPUT
        env:
          SNAPSTORE_KEY: ${{ secrets.STORE_LOGIN }}

  promote-to-stable:
    runs-on: ubuntu-22.04
    needs: [check-secret]
    steps:
      - if: needs.check-secret.outputs.snap-key == 'true'
        name : Remove Docker
        run: |
          # https://github.com/canonical/lxd-cloud/blob/f20a64a8af42485440dcbfd370faf14137d2f349/test/includes/lxd.sh#L13-L23
          sudo rm -rf /etc/docker
          sudo apt-get purge moby-buildx moby-engine moby-cli moby-compose moby-containerd moby-runc -y
          sudo iptables -P FORWARD ACCEPT

      - if: needs.check-secret.outputs.snap-key == 'true'
        name: Publish snap stable release
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: |
          sudo snap install snapcraft --classic
          snapcraft promote checkbox-kivu-classic --from-channel latest/beta --to-channel latest/candidate --yes
          snapcraft promote checkbox-kivu-classic --from-channel latest/candidate --to-channel latest/stable --yes

